spring:
  profiles:
    include: oauth

  session:
    store-type: jdbc

  datasource:
    hikari: #real-db를 사용할 경우 override
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      data-username: sa

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
        format_sql: true

  h2:
    console:
      enabled: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE