spring:
  profiles:
    include: oauth

  session:
    store-type: jdbc

  datasource:
    url: jdbc:h2:mem:testdb
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE